from Utils.Strings import emptyString


class Contact:
    def __init__(self, username: str = emptyString, cell: str = emptyString, org: str = emptyString,
                 note: str = "This contact automatically generated by "
                             "Shalaga44"):
        self.username = username.strip()
        self.cell = cell.strip()
        self.org = org.strip()
        self.note = note.strip()
        self.email = emptyString
        self.title = emptyString

    def __str__(self):
        return self.username

    def __repr__(self):
        return self.__str__()
